### ISSUE TITLE
Add buckets to bower and npm

### ISSUE THREAD

**Issue by nvlbg** [mauriciosantos/buckets#5]
It would be nice if you can install the library from a package manager instead of downloading it manually.

**Comment by nvlbg** [comment]
@mauriciosantos After https://github.com/mauriciosantos/buckets/pull/9 has been merged I have registered buckets both in npm and bower. Bower doesn't want maintainer when registering but npm does and it is under my account. I can remove it so you publish it from your own if you want to. Otherwise this issue must be closed :)

**Comment by mauriciosantos** [comment]
You can remove it and will publish it.

**Comment by nvlbg** [comment]
@mauriciosantos I'm sorry but I don't quite understood what you meant. Do you want me to unregister it from npm? I just wanna be sure there is no miscommunication.

**Comment by mauriciosantos** [comment]
yeah. that's right.

**Comment by nvlbg** [comment]
Ok, the project is unpublished.
